kind: pipeline
name: hello-world123
type: docker

steps:
  - name: say-hello
    image: node:latest
    commands:
      - node test.js

  - name: notify
    image: drillster/drone-email
    settings:
      from: noreply@github.com
      host: smtp.mailgun.org
      username: octocat
      password: 12345
      recipients:
        - shinegojoe@gmail.com

  # - name: say-hello2
  #   image: node:latest
  #   commands:
  #     - bash test2.sh
  #     - npm install
  #     - npm run standard-test