version: '2'
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      # github
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT_ID=deea7d7b4f635516d260
      - DRONE_GITHUB_CLIENT_SECRET=4097dfe394cc14b68cfa7b334a708b722387b358


      # setting
      - DRONE_SERVER_HOST=t-shirtcreator.com
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=ec9165664ef6f69554bdb38c7a24ad61
        #- DRONE_RUNNER_CAPACITY=3                                      # 表示一次可執行 n 個 job
        #- DRONE_GIT_ALWAYS_AUTH=false                                  # Drone clone 時，是否每次都驗證
        #- DRONE_USER_FILTER=root                                       # 可操作 Drone 的用戶清單
        #- DRONE_USER_CREATE=username:root:true

  drone-agent:
    image: drone/drone-runner-docker:1
    # command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
            #- DRONE_SERVER=drone-server:9000
      - DRONE_RPC_SECRET=ec9165664ef6f69554bdb38c7a24ad61
      - DRONE_RPC_PROTO=http
        # - DRONE_RPC_SERVER=drone-server
      - DRONE_RUNNER_NAME=rr
      - DRONE_RPC_HOST=t-shirtcreator.com
            #- DRONE_RPC_SECRET=drone-secret
      - DRONE_RUNNER_CAPACITY=2
            #- DRONE_LOGS_DEBUG=true




