version: '2'
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT_ID=deea7d7b4f635516d260
      - DRONE_GITHUB_CLIENT_SECRET=4097dfe394cc14b68cfa7b334a708b722387b358

      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_SERVER_HOST=t-shirtcreator.com
      - DRONE_SERVER_PROTO=http
  drone-agent:
    image: drone/agent:1
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
